apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-service-deployment
  labels:
    app: seller-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seller-service
  template:
    metadata:
      labels:
        app: seller-service
    spec:
      containers:
      - name: seller-service
        image: systeamorg/seller-service
        imagePullPolicy: Never
        ports:
        - containerPort: 82

---
apiVersion: v1
kind: Service
metadata:
  name: seller-service
  labels:
    app: seller-service
spec:
  ports:
  - port: 82
    targetPort: 82
    protocol: TCP
    name: tcp
    nodePort: 30082
  type: NodePort
  selector:
    app: seller-service
